### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'metadata/binance_keys.txt'

### ISSUE THREAD

**Issue by aictborder** [benedictmc/Final-Year-Project#1]
I found that the program could not run, maybe some files were missing.

Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
FileNotFoundError: [Errno 2] No such file or directory: 'metadata/binance_keys.txt'

**Comment by aictborder** [comment]
2019-11-16 01:36:57.654371: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
Starting trading simulator for coin BTC...
Traceback (most recent call last):
  File "C:/Users/te/Desktop/GAN_test/Final-Year-Project-master/Final-Year-Project-master/trading_simulator.py", line 160, in <module>
    x = TradingSimulator('BTC')
  File "C:/Users/te/Desktop/GAN_test/Final-Year-Project-master/Final-Year-Project-master/trading_simulator.py", line 18, in __init__
    with open('metadata/binance_keys.txt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'metadata/binance_keys.txt'

**Comment by benedictmc** [comment]
Hi this is caused because I have not included this file. You can create this file with your own binance keys in order to download real time data.
